In [59]:
import pandas as pd

In [60]:
#chargement des logs dhcp
jeu1dhcp = pd.read_table("C:\\Users\\viann\\PT\\user_behavior\\DhcpSrvLog-Jeu.log", encoding='latin1', low_memory=False)
jeu2dhcp = pd.read_table("C:\\Users\\viann\\PT\\user_behavior\\DhcpSrvLog-Ven.log", encoding='latin1',low_memory=False)
jeu3dhcp = pd.read_table("C:\\Users\\viann\\PT\\user_behavior\\DhcpSrvLog-Sam.log", encoding='latin1')
jeu4dhcp = pd.read_table("C:\\Users\\viann\\PT\\user_behavior\\DhcpSrvLog-Dim.log", encoding='latin1')
jeu5dhcp = pd.read_table("C:\\Users\\viann\\PT\\user_behavior\\DhcpSrvLog-Lun.log", encoding='latin1',low_memory=False)
jeu6dhcp = pd.read_table("C:\\Users\\viann\\PT\\user_behavior\\DhcpSrvLog-Mar.log", encoding='latin1',low_memory=False)
jeu7dhcp = pd.read_table("C:\\Users\\viann\\PT\\user_behavior\\DhcpSrvLog-Mer.log", encoding='latin1')

In [61]:
#chargement des logs dhcp
jeu1dhcpv6 = pd.read_csv("C:\\Users\\viann\\PT\\user_behavior\\DhcpV6SrvLog-Sam.log", encoding='latin1',skiprows=34,delimiter=',',usecols=range(12))
jeu2dhcpv6 = pd.read_table("C:\\Users\\viann\\PT\\user_behavior\\DhcpV6SrvLog-Dim.log", encoding='latin1',skiprows=34,delimiter=',',usecols=range(12))

In [62]:
#pretraitement dhcpv6
dhcpv6 = pd.concat([jeu1dhcpv6,jeu2dhcpv6], ignore_index=True)
dhcpv6=dhcpv6.iloc[:,:3]
dhcpv6

       ID      Date     Heure
0   11020  07/25/20  00:00:08
1   11019  07/25/20  00:00:08
2   11021  07/25/20  00:00:08
3   11030  07/25/20  00:26:08
4   11030  07/25/20  01:26:10
5   11030  07/25/20  02:26:13
6   11030  07/25/20  03:26:16
7   11030  07/25/20  04:26:18
8   11030  07/25/20  05:26:21
9   11030  07/25/20  06:26:24
10  11030  07/25/20  07:26:27
11  11030  07/25/20  08:26:29
12  11030  07/25/20  09:26:32
13  11030  07/25/20  10:26:35
14  11030  07/25/20  11:26:38
15  11030  07/25/20  12:26:41
16  11030  07/25/20  13:26:43
17  11030  07/25/20  14:26:46
18  11030  07/25/20  15:26:49
19  11030  07/25/20  16:26:51
20  11030  07/25/20  17:26:54
21  11030  07/25/20  18:26:57
22  11030  07/25/20  19:27:00
23  11030  07/25/20  20:27:02
24  11030  07/25/20  21:27:05
25  11030  07/25/20  22:27:08
26  11030  07/25/20  23:27:11
27  11020  07/26/20  00:00:13
28  11019  07/26/20  00:00:13
29  11021  07/26/20  00:00:13
30  11030  07/26/20  00:27:13
31  11030  07/26/20  01:27:16
32  11030  07/26/20  02:27:19
33  11030  07/26/20  03:27:21
34  11030  07/26/20  04:27:24
35  11030  07/26/20  05:27:27
36  11030  07/26/20  06:27:29
37  11030  07/26/20  07:27:32
38  11030  07/26/20  08:27:34
39  11030  07/26/20  09:27:37
40  11030  07/26/20  10:27:39
41  11030  07/26/20  11:27:42
42  11030  07/26/20  12:27:44
43  11030  07/26/20  13:27:47
44  11030  07/26/20  14:27:50
45  11030  07/26/20  15:27:52
46  11030  07/26/20  16:27:55
47  11030  07/26/20  17:27:57
48  11030  07/26/20  18:28:00
49  11030  07/26/20  19:28:02
50  11030  07/26/20  20:28:05
51  11030  07/26/20  21:28:07
52  11030  07/26/20  22:28:10
53  11030  07/26/20  23:28:13

In [63]:
#coller les dhcp
dhcplog=pd.concat([jeu1dhcp,jeu2dhcp,jeu3dhcp,jeu4dhcp,jeu5dhcp,jeu6dhcp,jeu7dhcp], ignore_index=True)
dhcplog=dhcplog.iloc[28:]

In [64]:
#pretraitement
new_cols = ["ID", "Date", "Heure", "Description", "Adresse IP", "Nom d'hôte",
            "Adresse MAC", "Nom d'utilisateur", "ID transaction", "Résultat Q",
            "Heure essai", "ID corrélation", "DHCID", "ClasseFournisseur (Hex)",
            "ClasseFournisseur (ASCII)", "ClasseUtilisateur (Hex)", "ClasseUtilisateur (ASCII)",
            "InformationsAgentRelais", "ErreurEnregistrementDNS"]
dhcplog[new_cols] = dhcplog['Unnamed: 0'].str.split(',', expand=True)

In [65]:
dhcplog=dhcplog.iloc[1:,0:]
dhcplog = dhcplog.drop(columns=['Unnamed: 0','Unnamed: 1'])

In [66]:
dhcplog=dhcplog[["ID", "Date", "Heure","Adresse IP", "Nom d'hôte",
            "Adresse MAC", "Nom d'utilisateur", "ID transaction", "Résultat Q",
            "Heure essai", "ID corrélation", "DHCID", "ClasseFournisseur (Hex)",
            "ClasseFournisseur (ASCII)", "ClasseUtilisateur (Hex)", "ClasseUtilisateur (ASCII)",
            "InformationsAgentRelais", "ErreurEnregistrementDNS"]]
dhcplog

,ID,Date,Heure,Adresse IP,Nom d'hôte,Adresse MAC,Nom d'utilisateur,ID transaction,Résultat Q,Heure essai,ID corrélation,DHCID,ClasseFournisseur (Hex),ClasseFournisseur (ASCII),ClasseUtilisateur (Hex),ClasseUtilisateur (ASCII),InformationsAgentRelais,ErreurEnregistrementDNS
29,24,07/23/20,00:00:51,,,,,0,6,,,,,,,,,0
30,30,07/23/20,00:00:51,192.168.1.31,SIP-T22P.ocitnetad.ci,,,0,6,,,,,,,,,0
31,30,07/23/20,00:00:51,192.168.1.32,EB-5CG627297H.ocitnetad.ci,,,0,6,,,,,,,,,0
32,30,07/23/20,00:00:51,192.168.1.33,android-cb0e95cc8b3a4b2f.ocitnetad.ci,,,0,6,,,,,,,,,0
33,30,07/23/20,00:00:51,192.168.1.35,EB-99JX6R1.ocitnetad.ci,,,0,6,,,,,,,,,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1682612,11,07/29/20,09:40:32,192.168.76.40,WX-5CG8528D2J.ocitnetad.ci,B00CD1360D57,,4286866700,0,,,,0x4D53465420352E30,MSFT 5.0,0x656275726F,eburo,,0
1682613,31,07/29/20,09:40:32,192.168.76.40,WX-5CG8528D2J.ocitnetad.ci,,,0,6,,,,,,,,,9501
1682614,30,07/29/20,09:40:32,192.168.136.70,WX-5CD94163ZM.ocitnetad.ci,,,0,6,,,,,,,,,0
1682615,10,07/29/20,09:40:32,192.168.136.70,WX-5CD94163ZM.ocitnetad.ci,DC71962D80C0,,4009751514,0,,,,0x4D53465420352E30,MSFT 5.0,,,,0
1682616,31,07/29/20,09:40:32,192.168.136.70,WX-5CD94163ZM.ocitnetad.ci,,,0,6,,,,,,,,,9501

In [67]:
new1=dhcplog.sort_values(by =["Adresse IP",'Date',"Heure"])
new1

,ID,Date,Heure,Adresse IP,Nom d'hôte,Adresse MAC,Nom d'utilisateur,ID transaction,Résultat Q,Heure essai,ID corrélation,DHCID,ClasseFournisseur (Hex),ClasseFournisseur (ASCII),ClasseUtilisateur (Hex),ClasseUtilisateur (ASCII),InformationsAgentRelais,ErreurEnregistrementDNS
29,24,07/23/20,00:00:51,,,,,0,6,,,,,,,,,0
2643,25,07/23/20,00:00:51,,,,,0,6,,,,,,,,,0
2644,25,07/23/20,00:00:51,,,,,0,6,,,,,,,,,0
5760,24,07/23/20,00:23:51,,,,,0,6,,,,,,,,,0
8336,25,07/23/20,00:23:51,,,,,0,6,,,,,,,,,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1572628,33,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1572629,34,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1572630,35,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1572631,36,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1572632,50+,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None

In [68]:
new1=new1.iloc[579:]
new1=new1.dropna()
new1.head(50)

,ID,Date,Heure,Adresse IP,Nom d'hôte,Adresse MAC,Nom d'utilisateur,ID transaction,Résultat Q,Heure essai,ID corrélation,DHCID,ClasseFournisseur (Hex),ClasseFournisseur (ASCII),ClasseUtilisateur (Hex),ClasseUtilisateur (ASCII),InformationsAgentRelais,ErreurEnregistrementDNS
1572634,ID,Date,Heure,Adresse IP,Nom d'hôte,Adresse MAC,Nom d'utilisateur,ID transaction,Résultat Q,Heure essai,ID corrélation,DHCID,ClasseFournisseur (Hex),ClasseFournisseur (ASCII),ClasseUtilisateur (Hex),ClasseUtilisateur (ASCII),InformationsAgentRelais,ErreurEnregistrementDNS.
95582,15,07/23/20,09:23:36,0.170.222.100,,00A859F79291,,0,6,,,,,,,,,0
95583,15,07/23/20,09:23:36,0.170.222.100,,00A859F79291,,0,6,,,,,,,,,0
95584,15,07/23/20,09:23:36,0.170.222.100,,00A859F79291,,0,6,,,,,,,,,0
95585,15,07/23/20,09:23:36,0.170.222.100,,00A859F79291,,0,6,,,,,,,,,0
95602,15,07/23/20,09:23:40,0.170.222.100,,00A859F79291,,0,6,,,,,,,,,0
95603,15,07/23/20,09:23:40,0.170.222.100,,00A859F79291,,0,6,,,,,,,,,0
95604,15,07/23/20,09:23:40,0.170.222.100,,00A859F79291,,0,6,,,,,,,,,0
95605,15,07/23/20,09:23:40,0.170.222.100,,00A859F79291,,0,6,,,,,,,,,0
95628,15,07/23/20,09:23:48,0.170.222.100,,00A859F79291,,0,6,,,,,,,,,0
95629,15,07/23/20,09:23:48,0.170.222.100,,00A859F79291,,0,6,,,,,,,,,0
95630,15,07/23/20,09:23:48,0.170.222.100,,00A859F79291,,0,6,,,,,,,,,0
95631,15,07/23/20,09:23:48,0.170.222.100,,00A859F79291,,0,6,,,,,,,,,0
95689,15,07/23/20,09:24:04,0.170.222.100,,00A859F79291,,0,6,,,,,,,,,0
95690,15,07/23/20,09:24:04,0.170.222.100,,00A859F79291,,0,6,,,,,,,,,0
95691,15,07/23/20,09:24:04,0.170.222.100,,00A859F79291,,0,6,,,,,,,,,0
95692,15,07/23/20,09:24:04,0.170.222.100,,00A859F79291,,0,6,,,,,,,,,0
99040,15,07/23/20,09:24:35,0.170.222.100,,00A859F79291,,0,6,,,,,,,,,0
99041,15,07/23/20,09:24:35,0.170.222.100,,00A859F79291,,0,6,,,,,,,,,0
99042,15,07/23/20,09:24:35,0.170.222.100,,00A859F79291,,0,6,,,,,,,,,0
99043,15,07/23/20,09:24:35,0.170.222.100,,00A859F79291,,0,6,,,,,,,,,0
1019961,15,07/27/20,08:50:03,10.0.0.2,,5CE0C51013F5,,0,6,,,,,,,,,0
1169320,15,07/27/20,16:39:05,10.0.2.15,,080027486AF4,,0,6,,,,,,,,,0
1169321,15,07/27/20,16:39:05,10.0.2.15,,080027486AF4,,0,6,,,,,,,,,0
1169322,15,07/27/20,16:39:05,10.0.2.15,,080027486AF4,,0,6,,,,,,,,,0
1072285,15,07/27/20,11:21:29,10.10.10.111,,78D75F7B22C1,,0,6,,,,,,,,,0
988560,15,07/27/20,06:53:52,10.10.10.237,,C486E9EEE44B,,0,6,,,,,,,,,0
467928,15,07/24/20,10:17:29,10.10.10.97,,9CAF6F9EDBB9,,0,6,,,,,,,,,0
131872,15,07/23/20,10:40:06,172.16.0.243,,E0B6F5D2EB43,,0,6,,,,,,,,,0
146850,15,07/23/20,11:28:08,172.16.0.243,,E0B6F5D2EB43,,0,6,,,,,,,,,0
242674,15,07/23/20,15:31:10,172.16.0.243,,E0B6F5D2EB43,,0,6,,,,,,,,,0
262036,15,07/23/20,16:32:05,172.16.0.243,,E0B6F5D2EB43,,0,6,,,,,,,,,0
1421802,15,07/28/20,12:48:38,172.16.50.17,,C486E9EED3FD,,0,6,,,,,,,,,0
537338,15,07/24/20,14:29:39,172.17.102.114,,4045DA5458F7,,0,6,,,,,,,,,0
66672,15,07/23/20,07:40:14,172.20.10.2,,F8FFC22292A3,,0,6,,,,,,,,,0
66673,15,07/23/20,07:40:14,172.20.10.2,,F8FFC22292A3,,0,6,,,,,,,,,0
66674,15,07/23/20,07:40:14,172.20.10.2,,F8FFC22292A3,,0,6,,,,,,,,,0
419874,15,07/24/20,08:19:24,172.20.10.2,,2016B9C31E82,,0,6,,,,,,,,,0
453926,15,07/24/20,09:27:45,172.20.10.2,,2816AD5D0642,,0,6,,,,,,,,,0
1016245,15,07/27/20,08:37:30,172.20.10.2,,E4B318D6801C,,0,6,,,,,,,,,0
1017209,15,07/27/20,08:41:14,172.20.10.2,,2816AD5D0462,,0,6,,,,,,,,,0
1190996,15,07/27/20,18:22:19,172.20.10.2,,D0FCCC92D353,,0,6,,,,,,,,,0
1658482,15,07/29/20,08:38:44,172.20.10.2,,F83441E8745C,,0,6,,,,,,,,,0
1661898,15,07/29/20,08:53:25,172.20.10.2,,F83441E874CF,,0,6,,,,,,,,,0
145204,15,07/23/20,11:25:30,172.20.10.3,,2016B993610B,,0,6,,,,,,,,,0
999842,15,07/27/20,07:55:35,172.20.10.3,,DC53604C0F95,,0,6,,,,,,,,,0
544067,15,07/24/20,15:15:51,172.20.10.4,,2816AD5D0647,,0,6,,,,,,,,,0
1004422,15,07/27/20,08:15:05,172.20.10.5,,D46A6AA7792D,,0,6,,,,,,,,,0
713179,15,07/25/20,09:59:00,172.31.246.228,,48BA4EF62F8F,,0,6,,,,,,,,,0
109453,15,07/23/20,09:59:50,172.31.247.150,,D09DAB2FEE40,,0,6,,,,,,,,,0

In [69]:
new1['Date'] = pd.to_datetime(new1['Date'], format='%m/%d/%y',errors='coerce')
new1['DateTime'] = new1['Date'].astype(str) + ' ' + new1['Heure']
new1['DateTime'] = pd.to_datetime(new1['DateTime'], errors='coerce')
new1['SessionDuration'] = new1.groupby(["Adresse IP","Date"])["DateTime"].diff()
new1.head(30)

C:\Users\viann\AppData\Local\Temp\ipykernel_26072\3578346760.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  new1['DateTime'] = pd.to_datetime(new1['DateTime'], errors='coerce')

,ID,Date,Heure,Adresse IP,Nom d'hôte,Adresse MAC,Nom d'utilisateur,ID transaction,Résultat Q,Heure essai,ID corrélation,DHCID,ClasseFournisseur (Hex),ClasseFournisseur (ASCII),ClasseUtilisateur (Hex),ClasseUtilisateur (ASCII),InformationsAgentRelais,ErreurEnregistrementDNS,DateTime,SessionDuration
1572634,ID,NaT,Heure,Adresse IP,Nom d'hôte,Adresse MAC,Nom d'utilisateur,ID transaction,Résultat Q,Heure essai,ID corrélation,DHCID,ClasseFournisseur (Hex),ClasseFournisseur (ASCII),ClasseUtilisateur (Hex),ClasseUtilisateur (ASCII),InformationsAgentRelais,ErreurEnregistrementDNS.,NaT,NaT
95582,15,2020-07-23,09:23:36,0.170.222.100,,00A859F79291,,0,6,,,,,,,,,0,2020-07-23 09:23:36,NaT
95583,15,2020-07-23,09:23:36,0.170.222.100,,00A859F79291,,0,6,,,,,,,,,0,2020-07-23 09:23:36,0 days 00:00:00
95584,15,2020-07-23,09:23:36,0.170.222.100,,00A859F79291,,0,6,,,,,,,,,0,2020-07-23 09:23:36,0 days 00:00:00
95585,15,2020-07-23,09:23:36,0.170.222.100,,00A859F79291,,0,6,,,,,,,,,0,2020-07-23 09:23:36,0 days 00:00:00
95602,15,2020-07-23,09:23:40,0.170.222.100,,00A859F79291,,0,6,,,,,,,,,0,2020-07-23 09:23:40,0 days 00:00:04
95603,15,2020-07-23,09:23:40,0.170.222.100,,00A859F79291,,0,6,,,,,,,,,0,2020-07-23 09:23:40,0 days 00:00:00
95604,15,2020-07-23,09:23:40,0.170.222.100,,00A859F79291,,0,6,,,,,,,,,0,2020-07-23 09:23:40,0 days 00:00:00
95605,15,2020-07-23,09:23:40,0.170.222.100,,00A859F79291,,0,6,,,,,,,,,0,2020-07-23 09:23:40,0 days 00:00:00
95628,15,2020-07-23,09:23:48,0.170.222.100,,00A859F79291,,0,6,,,,,,,,,0,2020-07-23 09:23:48,0 days 00:00:08
95629,15,2020-07-23,09:23:48,0.170.222.100,,00A859F79291,,0,6,,,,,,,,,0,2020-07-23 09:23:48,0 days 00:00:00
95630,15,2020-07-23,09:23:48,0.170.222.100,,00A859F79291,,0,6,,,,,,,,,0,2020-07-23 09:23:48,0 days 00:00:00
95631,15,2020-07-23,09:23:48,0.170.222.100,,00A859F79291,,0,6,,,,,,,,,0,2020-07-23 09:23:48,0 days 00:00:00
95689,15,2020-07-23,09:24:04,0.170.222.100,,00A859F79291,,0,6,,,,,,,,,0,2020-07-23 09:24:04,0 days 00:00:16
95690,15,2020-07-23,09:24:04,0.170.222.100,,00A859F79291,,0,6,,,,,,,,,0,2020-07-23 09:24:04,0 days 00:00:00
95691,15,2020-07-23,09:24:04,0.170.222.100,,00A859F79291,,0,6,,,,,,,,,0,2020-07-23 09:24:04,0 days 00:00:00
95692,15,2020-07-23,09:24:04,0.170.222.100,,00A859F79291,,0,6,,,,,,,,,0,2020-07-23 09:24:04,0 days 00:00:00
99040,15,2020-07-23,09:24:35,0.170.222.100,,00A859F79291,,0,6,,,,,,,,,0,2020-07-23 09:24:35,0 days 00:00:31
99041,15,2020-07-23,09:24:35,0.170.222.100,,00A859F79291,,0,6,,,,,,,,,0,2020-07-23 09:24:35,0 days 00:00:00
99042,15,2020-07-23,09:24:35,0.170.222.100,,00A859F79291,,0,6,,,,,,,,,0,2020-07-23 09:24:35,0 days 00:00:00
99043,15,2020-07-23,09:24:35,0.170.222.100,,00A859F79291,,0,6,,,,,,,,,0,2020-07-23 09:24:35,0 days 00:00:00
1019961,15,2020-07-27,08:50:03,10.0.0.2,,5CE0C51013F5,,0,6,,,,,,,,,0,2020-07-27 08:50:03,NaT
1169320,15,2020-07-27,16:39:05,10.0.2.15,,080027486AF4,,0,6,,,,,,,,,0,2020-07-27 16:39:05,NaT
1169321,15,2020-07-27,16:39:05,10.0.2.15,,080027486AF4,,0,6,,,,,,,,,0,2020-07-27 16:39:05,0 days 00:00:00
1169322,15,2020-07-27,16:39:05,10.0.2.15,,080027486AF4,,0,6,,,,,,,,,0,2020-07-27 16:39:05,0 days 00:00:00
1072285,15,2020-07-27,11:21:29,10.10.10.111,,78D75F7B22C1,,0,6,,,,,,,,,0,2020-07-27 11:21:29,NaT
988560,15,2020-07-27,06:53:52,10.10.10.237,,C486E9EEE44B,,0,6,,,,,,,,,0,2020-07-27 06:53:52,NaT
467928,15,2020-07-24,10:17:29,10.10.10.97,,9CAF6F9EDBB9,,0,6,,,,,,,,,0,2020-07-24 10:17:29,NaT
131872,15,2020-07-23,10:40:06,172.16.0.243,,E0B6F5D2EB43,,0,6,,,,,,,,,0,2020-07-23 10:40:06,NaT
146850,15,2020-07-23,11:28:08,172.16.0.243,,E0B6F5D2EB43,,0,6,,,,,,,,,0,2020-07-23 11:28:08,0 days 00:48:02

In [70]:
new1=new1[["ID", "Date", "Heure","Adresse IP", "Nom d'hôte",
            "Adresse MAC","DateTime","SessionDuration"]]
new1=new1.iloc[1:]
new1

,ID,Date,Heure,Adresse IP,Nom d'hôte,Adresse MAC,DateTime,SessionDuration
95582,15,2020-07-23,09:23:36,0.170.222.100,,00A859F79291,2020-07-23 09:23:36,NaT
95583,15,2020-07-23,09:23:36,0.170.222.100,,00A859F79291,2020-07-23 09:23:36,0 days 00:00:00
95584,15,2020-07-23,09:23:36,0.170.222.100,,00A859F79291,2020-07-23 09:23:36,0 days 00:00:00
95585,15,2020-07-23,09:23:36,0.170.222.100,,00A859F79291,2020-07-23 09:23:36,0 days 00:00:00
95602,15,2020-07-23,09:23:40,0.170.222.100,,00A859F79291,2020-07-23 09:23:40,0 days 00:00:04
...,...,...,...,...,...,...,...,...
102796,15,2020-07-23,09:35:50,208.167.222.100,,00A859F79291,2020-07-23 09:35:50,0 days 00:00:08
102797,15,2020-07-23,09:35:50,208.167.222.100,,00A859F79291,2020-07-23 09:35:50,0 days 00:00:00
102798,15,2020-07-23,09:35:50,208.167.222.100,,00A859F79291,2020-07-23 09:35:50,0 days 00:00:00
102799,15,2020-07-23,09:35:50,208.167.222.100,,00A859F79291,2020-07-23 09:35:50,0 days 00:00:00
512796,15,2020-07-24,13:21:53,30.68.170.21,,909497574BCE,2020-07-24 13:21:53,NaT

In [71]:
new1 = new1.dropna(subset=['SessionDuration'])
Q1 = new1['SessionDuration'].quantile(0.25)
Q3 = new1['SessionDuration'].quantile(0.75)
IQR = Q3 - Q1

seuil_bas = Q1 - 1.5 * IQR
seuil_haut = Q3 + 1.5 * IQR

In [72]:
new1['Anomalies']=0
new1.loc[(new1['SessionDuration'] < seuil_bas) | (new1['SessionDuration'] > seuil_haut), 'Anomalies'] = 1

C:\Users\viann\AppData\Local\Temp\ipykernel_26072\1725185999.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new1['Anomalies']=0

In [73]:
new1

,ID,Date,Heure,Adresse IP,Nom d'hôte,Adresse MAC,DateTime,SessionDuration,Anomalies
95583,15,2020-07-23,09:23:36,0.170.222.100,,00A859F79291,2020-07-23 09:23:36,0 days 00:00:00,0
95584,15,2020-07-23,09:23:36,0.170.222.100,,00A859F79291,2020-07-23 09:23:36,0 days 00:00:00,0
95585,15,2020-07-23,09:23:36,0.170.222.100,,00A859F79291,2020-07-23 09:23:36,0 days 00:00:00,0
95602,15,2020-07-23,09:23:40,0.170.222.100,,00A859F79291,2020-07-23 09:23:40,0 days 00:00:04,0
95603,15,2020-07-23,09:23:40,0.170.222.100,,00A859F79291,2020-07-23 09:23:40,0 days 00:00:00,0
...,...,...,...,...,...,...,...,...,...
102769,15,2020-07-23,09:35:42,208.167.222.100,,00A859F79291,2020-07-23 09:35:42,0 days 00:00:00,0
102796,15,2020-07-23,09:35:50,208.167.222.100,,00A859F79291,2020-07-23 09:35:50,0 days 00:00:08,0
102797,15,2020-07-23,09:35:50,208.167.222.100,,00A859F79291,2020-07-23 09:35:50,0 days 00:00:00,0
102798,15,2020-07-23,09:35:50,208.167.222.100,,00A859F79291,2020-07-23 09:35:50,0 days 00:00:00,0
102799,15,2020-07-23,09:35:50,208.167.222.100,,00A859F79291,2020-07-23 09:35:50,0 days 00:00:00,0

In [75]:
newdataset=new1.drop(columns=["Adresse MAC","Nom d'hôte"])
newdataset

,ID,Date,Heure,Adresse IP,DateTime,SessionDuration,Anomalies
95583,15,2020-07-23,09:23:36,0.170.222.100,2020-07-23 09:23:36,0 days 00:00:00,0
95584,15,2020-07-23,09:23:36,0.170.222.100,2020-07-23 09:23:36,0 days 00:00:00,0
95585,15,2020-07-23,09:23:36,0.170.222.100,2020-07-23 09:23:36,0 days 00:00:00,0
95602,15,2020-07-23,09:23:40,0.170.222.100,2020-07-23 09:23:40,0 days 00:00:04,0
95603,15,2020-07-23,09:23:40,0.170.222.100,2020-07-23 09:23:40,0 days 00:00:00,0
...,...,...,...,...,...,...,...
102769,15,2020-07-23,09:35:42,208.167.222.100,2020-07-23 09:35:42,0 days 00:00:00,0
102796,15,2020-07-23,09:35:50,208.167.222.100,2020-07-23 09:35:50,0 days 00:00:08,0
102797,15,2020-07-23,09:35:50,208.167.222.100,2020-07-23 09:35:50,0 days 00:00:00,0
102798,15,2020-07-23,09:35:50,208.167.222.100,2020-07-23 09:35:50,0 days 00:00:00,0
102799,15,2020-07-23,09:35:50,208.167.222.100,2020-07-23 09:35:50,0 days 00:00:00,0